Switch from google maps to openstreetmaps
umts/incidents pull request #443
Opened 2024-05-13 21:04 UTC by benmelz

Uses leaflet as client library for rendering the map (definitely small/lightweight enough, and doesn't require modules to build), openstreetmaps for the map tiles and nominatum (free openstreetmaps geocoder) for reverse geocoding.

On nominatum, there are [netizen guidelines](https://operations.osmfoundation.org/policies/nominatim/) to follow. I don't _think_ we're gonna be too much of a nuisance? But the other alternative that I can think of that doesn't involve google is esri (esp. since umass is already paying them/even hosting our own instances I think).

2024-05-13 21:12 UTC, benmelz commented on app/assets/javascripts/latlong_map.coffee
> -        createMap mapSelector, PVTA, false
Oh, I didn't end up preserving this feature, which is basically "If we don't have an initial lat/long, try to geocode what's already in the address fields and use that"

It didn't seem like a needed feature based on what I understand about the workflows, so I didn't bother with it

2024-05-15 19:57 UTC, werebus requested changes

2024-05-15 20:25 UTC, werebus commented on app/assets/javascripts/incident_reports/form.js
> +      headers: {'User-Agent': 'PVTAIncidents/1.0'}, // play nice and identify ourselves
I'll mention that the requirement is for a Referer _or_ a User-Agent. This is fine, but might not be strictly necessary.

2024-05-15 20:29 UTC, werebus commented on app/assets/javascripts/incident_reports/form.js
> +      headers: {'User-Agent': 'PVTAIncidents/1.0'}, // play nice and identify ourselves
Changed my mind. If we're using it in development, I don't think `http://localhost:3000/` is tremendously useful to them in identifying who's abusing their service.

2024-05-16 15:16 UTC, werebus approved these changes

2024-05-16 17:41 UTC, merged